name: cron test

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: time check
        run: date

      - name: alive check
        run: echo "cron is alive"
